name: Java maven build github workflow

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: './'
      jar-file-path:
        required: false
        type: string
        default: 'target/'
      java-version:
        required: false
        type: string
        default: '17'
      app-name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  maven-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: corretto
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory contents
        run: |
          echo "Working directory: $(pwd)"
          ls -la target/
          ls -la target/*.jar || echo "No JAR files found"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ inputs.app-name }}-java
          path: ${{ inputs.working-directory }}/target/*.jar
          if-no-files-found: error